######################################################################
# Automatically generated by qmake (2.01a) Sat May 9 01:15:28 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . libnxtbt/include
LIBS += -lcwiimote -L libnxtbt/src -lnxtbt

# Input
HEADERS += mainwindow.h connectdialog.h
SOURCES += main.cpp mainwindow.cpp connectdialog.cpp
FORMS   += connectdialog.ui
